
INSERT INTO PRODUTO(ID,NOME,PRECO,DESCRICAO) VALUES(1,'Kindle',499.0,'novo Kindle');
INSERT INTO PRODUTO(ID,NOME,PRECO,DESCRICAO) VALUES(3,'Camera goPro Hero',1500.0,'melhor desempenho');

INSERT INTO CLIENTE(ID,NOME) VALUES(1,"Joao");
INSERT INTO CLIENTE(ID,NOME) VALUES(2,"Maria");